import { NavBar } from '@/components/NavBar'
import './globals.css'
import { Source_Code_Pro } from 'next/font/google'

const sourceCodePro = Source_Code_Pro({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={sourceCodePro.className}>
        <NavBar/>
        {children}
      </body>
    </html>
  )
}
